# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuelphFoodGuideSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='restaurantMenu',
            field=models.URLField(max_length=500),
        ),
    ]
