# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuelphFoodGuideSite', '0002_auto_20170924_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dietaryRestrictions',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
