# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuelphFoodGuideSite', '0004_resource_pricepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='onOrOffCampus',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=3),
        ),
    ]
