# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuelphFoodGuideSite', '0005_resource_onoroffcampus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='restaurantMenu',
            field=models.TextField(default='abc', max_length=500),
        ),
    ]
